import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Button, Checkbox, Input, Swap, Table } from "react-daisyui";
import { useAirtable } from "@/hooks/useAirtable";
import { FormModule } from "@/modules/FormModule";
import { useState } from "react";
import { useAtom, useAtomValue } from "jotai";
import {
  apiKeyAtomPersist,
  baseIdAtomPersist,
  savedFileAtomsPersist,
} from "@/hooks/useLocalStorage";

export default function Home() {
  const [isFetching, setIsFetching] = useState(false);
  const [apiKey, setApiAtom] = useAtom(apiKeyAtomPersist);
  const [baseId, setBaseIdAtom] = useAtom(baseIdAtomPersist);
  const savedFiles = useAtomValue(savedFileAtomsPersist);
  const { data, isLoading } = useAirtable(isFetching, baseId, apiKey);
  if (isLoading) return null;

  return (
    <>
      <Head>
        <title>Airtable to JSON Resume</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.sidebar}>
          <div className={styles.apiForm}>
            <div>
              <p>Instructions</p>
              <p>
                1. Copy this template -
                https://airtable.com/shrqGGJxmNJaqN3oS/tbl98mpJWHLe8P5gc/viwCjlPQnN1LZB9kU.
                and fill it in with your information. 2. Get your Airtable API
                key and base id from Airtable Developer Hub -
                https://airtable.com/create/tokens.
              </p>
            </div>
            <Input
              type="text"
              placeholder="Enter Airtable API KEY"
              color="info"
              value={apiKey}
              onChange={(e) => setApiAtom(e.target.value)}
            />
            <Input
              type="text"
              placeholder="Enter Airtable Table ID"
              color="info"
              value={baseId}
              onChange={(e) => setBaseIdAtom(e.target.value)}
            />
            <Button variant="outline" onClick={() => setIsFetching(true)}>
              Submit
            </Button>
          </div>
          <div className={styles.pastResumes}>
            <Table>
              <Table.Head>
                <span />
                <span>Past Resumes</span>
                <span>date</span>
              </Table.Head>
              <Table.Body>
                {savedFiles &&
                  savedFiles?.map((file, idx) => (
                    <Table.Row key={idx}>
                      <span>{idx}</span>
                      <span>{file.filename}</span>
                      <span>{file.date}</span>
                    </Table.Row>
                  ))}
              </Table.Body>
            </Table>
          </div>
        </div>
        {data && <FormModule data={data} />}
      </main>
    </>
  );
}
