import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Button, Checkbox, Input, Swap, Table } from "react-daisyui";
import { useAirtable } from "@/hooks/useAirtable";
import { FormModule } from "@/modules/FormModule";
import { useEffect, useState } from "react";

export default function Home() {
  const [isFetching, setIsFetching] = useState(true);
  const [baseId, setBaseId] = useState("app9vXnmaVThM60pi");
  const [apiKey, setApiKey] = useState(
    "patfnwnHmUX1Iv9Df.484ca78297f79a54a0eb2560b2732aedcbb2ffe295a73f694cb7758d41a49899"
  );
  const { data, isLoading } = useAirtable(isFetching, baseId, apiKey);

  useEffect(() => {}, [data]);

  if (isLoading) return null;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.sidebar}>
          <div className={styles.apiForm}>
            <Input
              type="text"
              placeholder="Enter Airtable API KEY"
              color="info"
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
            />
            <Input
              type="text"
              placeholder="Enter Airtable Table ID"
              color="info"
              value={baseId}
              onChange={(e) => setBaseId(e.target.value)}
            />
            <Button variant="outline" onClick={() => setIsFetching(true)}>
              Submit
            </Button>
          </div>
          <div className={styles.pastResumes}>
            <Table>
              <Table.Head>
                <span />
                <span>Past Resumes</span>
                <span>date</span>
              </Table.Head>
              <Table.Body>
                <Table.Row>
                  <span>1</span>
                  <span>google_hire</span>
                  <span>2023.01.04</span>
                </Table.Row>
                <Table.Row>
                  <span>2</span>
                  <span>post-grad-amazon</span>
                  <span>2023.01.04</span>
                </Table.Row>
              </Table.Body>
            </Table>
          </div>
        </div>
        <FormModule data={data} />
      </main>
    </>
  );
}
